{{- if .Values.firewallCa.externalSecretRef }}
kind: ExternalSecret
apiVersion: external-secrets.io/v1
metadata:
  name: firewall-ca-cert
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mcd-agent-secret-store
  target:
    name: firewall-ca-cert
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: {{ .Values.firewallCa.externalSecretRef }}
{{- end }}
