{{- if not .Values.skipExternalSecrets }}
kind: ExternalSecret
apiVersion: external-secrets.io/v1
metadata:
  name: mcd-integrations-secrets
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
spec:
  {{- if and .Values.integrationsSecrets .Values.integrationsSecrets.data }}
  data:
    {{- range .Values.integrationsSecrets.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef: {{ .remoteRef | toYaml | nindent 8 }}
    {{- end }}
  {{- else }}
  data:
    # This is a dummy secret as we cannot create an empty external secret
    # We need to reference a valid remote ref here, to pass validations,
    # but it will be replaced by the template empty JSON below.
    - secretKey: empty.json
      remoteRef: {{ ((.Values.tokenSecret).remoteRef | default (.Values.oauthSecret).remoteRef) | toYaml | nindent 8 }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: mcd-agent-secret-store
  target:
    name: mcd-integrations-secrets
    creationPolicy: {{ (.Values.integrationsSecrets | default dict).targetCreationPolicy | default "Owner" | quote }}
    {{- if or (not .Values.integrationsSecrets) (not .Values.integrationsSecrets.data) }}
    # If no data is provided, create an empty secret as data is required
    template:
      mergePolicy: "Replace"
      data:
        empty.json: "{}"
    {{- end }}
  refreshInterval: {{ (.Values.integrationsSecrets | default dict).refreshInterval | default "1h" | quote }}
{{- end }}
