kind: ExternalSecret
apiVersion: external-secrets.io/v1
metadata:
  name: mcd-integrations-secrets
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
spec:
  {{- if .Values.integrationsSecrets.data }}
  data:
    {{ range .Values.integrationsSecrets.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef: {{ .remoteRef | toYaml | nindent 8 }}
    {{ end }}
  {{- else }}
  data:
    # This is a dummy secret as we cannot create an empty external secret
    - secretKey: empty.json
      remoteRef: {{ .Values.tokenSecret.remoteRef | toYaml | nindent 8 }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: mcd-agent-secret-store
  target:
    name: mcd-integrations-secrets
    creationPolicy: {{ .Values.integrationsSecrets.targetCreationPolicy | default "Owner" | quote }}
  refreshInterval: {{ .Values.integrationsSecrets.refreshInterval | default "1h" | quote }}
