kind: SecretStore
apiVersion: external-secrets.io/v1
metadata:
  name: mcd-agent-secret-store
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
spec: {{ .Values.secretStore | toYaml | nindent 4 }}
