apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcd-agent-service-account
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
  {{- if and .Values.serviceAccount .Values.serviceAccount.annotations }}
  annotations: {{ .Values.serviceAccount.annotations | toYaml | nindent 4 }}
  {{- end }}
