apiVersion: v1
kind: Service 
metadata:
  name: mcd-agent-loadbalancer-service
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
  {{- if .Values.service.annotations }}
  annotations: {{ .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    app: mcd-agent
  ports: 
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
{{- if .Values.service.loadBalancer -}}
  {{- if .Values.service.loadBalancer.sourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancer.sourceRanges | nindent 4 }}
  {{- end }}
{{- end }}
