{{- if and (not .Values.skipExternalSecrets) ((.Values.tokenSecret).remoteRef) }}
kind: ExternalSecret
apiVersion: external-secrets.io/v1
metadata:
  name: mcd-agent-token-secret
  namespace: {{ .Values.namespace | default "mcd-agent" | quote }}
spec:
  data:
    - secretKey: contents.json
      remoteRef: {{ .Values.tokenSecret.remoteRef | toYaml | nindent 8 }}
  secretStoreRef:
    kind: SecretStore
    name: mcd-agent-secret-store
  target:
    name: mcd-agent-token-secret
    creationPolicy: {{ .Values.tokenSecret.targetCreationPolicy | default "Owner" | quote }}
  refreshInterval: {{ .Values.tokenSecret.refreshInterval | default "1h" | quote }}
{{- end }}
