version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  helm: circleci/helm@3.2.0

commands:
  verify-version-in-docker-image:
    parameters:
      image:
        description: Image name to validate
        type: string
      version:
        description: Expected contents for /app/hermes/agent/version file
        type: string
    steps:
    - run:
        name: Verify version in Docker image
        command: |
          image_version=$(docker run --rm --entrypoint python << parameters.image >> hermes/agent/settings.py)
          if [ $image_version = "<< parameters.version >>" ]
            then exit 0
            else echo "Failed to find expected version, found: $image_version"; exit 1
          fi
  generate-version-number-dev:
    steps:
    - run:
        command: |
          PIPELINE_NUMBER=<< pipeline.number >>
          if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else TAG="v0.0.0"; fi
          VERSION=${TAG#v}
          echo "NEXT_VERSION=$(echo "$VERSION" | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')rc${PIPELINE_NUMBER}" >> $BASH_ENV
          source $BASH_ENV
        name: Generate dev version number
  generate-version-number-prod:
    steps:
    - run:
        command: |
          if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else TAG="v0.0.0"; fi
          echo "VERSION_TAG=${TAG#v}" >> $BASH_ENV
          source $BASH_ENV
        name: Generate prod version number

jobs:
  run-linter:
    docker:
      - image: cimg/python:3.12-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --no-cache-dir --upgrade pip
            pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
      - run:
          name: 'Run black / pyright'
          command: |
            . .venv/bin/activate
            black --check .
            pyright

  run-test-docker:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/build:
          image: mcd/hermes-agent-tests
          extra_build_args: --target tests
          step-name: Run tests in docker build

  build-and-push:
    machine:
      image: ubuntu-2204:current
    parameters:
      docker_hub_repository:
        type: string
      code_version:
        type: string
    steps:
      - checkout
      - docker/check:
          use-docker-credentials-store: true
      - docker/build:
          step-name: Build hermes image
          use-buildkit: true  # to build only the required stages
          extra_build_args: --target hermes-generic --build-arg code_version=<< parameters.code_version >> --build-arg build_number=<< pipeline.number >>
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-hermes,<< parameters.code_version >>-hermes
      - verify-version-in-docker-image:
          image: montecarlodata/<< parameters.docker_hub_repository >>:latest-hermes
          version: << parameters.code_version >>,<< pipeline.number >>
      - docker/push:
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-hermes,<< parameters.code_version >>-hermes

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - run-linter
      - run-test-docker:
          # run for all tags and branches, we need to add this so the job is available for build-and-push-prod
          filters:
            tags:
              only: /.*/
      - build-and-push:
          name: build-and-push-dev
          docker_hub_repository: pre-release-agent
          code_version: ${NEXT_VERSION}
          pre-steps:
            - checkout
            - generate-version-number-dev
          context:
            - docker
          requires:
            - run-linter
            - run-test-docker
          filters:
            branches:
              only:
                - dev
                - /.*\/pr-.*/
      - build-and-push:
          name: build-and-push-prod
          docker_hub_repository: agent
          code_version: ${VERSION_TAG}
          pre-steps:
            - checkout
            - generate-version-number-prod
          context:
            - docker
          requires:
            - run-linter
            - run-test-docker
          filters: # run only for tags starting with v, don't run for branches
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
